### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dym-sh** [hundredrabbits/Noodle#6]
im currently doing some work on a fork,
like adding toolbar to make usable on touch-only devices,
not sure yet if this will be a complete rewrite wich wouldn't require source repo to have a license,
but that's still a reasonable thing overall.

**Comment by neauoire** [comment]
Just added MIT, forgot about that :)
thanks!

**Comment by dym-sh** [comment]
dont forget to merge that branch into master :)
